<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Editar Participante
  </div>
  <div class="card-body">
   
      <form method="POST" 
      action="" enctype="multipart/form-data">
        
        <div class="form-group">
              
              <label for="id">Id:</label>
              <input type="text" class="form-control" readonly="true" value="" name="id"/>
          </div>

          <div class="form-group">
              
              <label for="nombre">Nombre:</label>
              <input type="text" value="" class="form-control" name="nombre"/>
          </div>
          <div class="form-group">
              
              <label for="curp">CURP:</label>
              <input type="text" value="" class="form-control" name="curp"/>
          </div>
          <div class="form-group">
              
              <label for="procedencia">Institución de procedencia:</label>
              <input type="text" value="" class="form-control" name="procedencia"/>
          </div>
          <div class="form-group">
              
              <label for="cuenta">Cuenta:</label>
              <input type="text" value="" class="form-control" name="cuenta"/>
          </div>
          <div class="form-group">
              
              <label for="password">Password:</label>
              <input type="password" value="" class="form-control" name="password"/>
          </div>
          
          <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
  </div>
</div>