<style>
  .uper {
    margin-top: 40px;
  }
</style>

  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>NOMBRE</td>
          <td>CURP</td>
          <td>INSTITUCION PROCEDENCIA</td>
          <td>CUENTA</td>
          <td>PASSWORD</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>

    <tbody>
      <!-- @foreach($categorias as $categoria)-->
      <tr>
        <td><!--{{$categoria->id}}--></td>
        <td><!--{{$categoria->descripcion}}--></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><a href="" 
             class="btn btn-primary">Edit</a></td>
        <td>
          <form action="" 
              method="post">
            
            <button class="btn btn-danger" type="submit" 
                onclick="" >Del</button>
          </form>
        </td>
      </tr>
     
    </tbody>

  </table>
<div>

