<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Editar Categoría
  </div>
  <div class="card-body">
      <br />
      <form method="POST" 
      action="" 
      enctype="multipart/form-data">
        <div class="form-group">
              <label for="id">Id:</label>
              <input type="text" 
              class="form-control" 
              readonly="true"
              value=""
              name="id"/>
          </div>

          <div class="form-group">
              <label for="descripcion">Categoría:</label>
              <input type="text" 
              value=""
              class="form-control" 
              name="descripcion"/>
          </div>
          
          <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
  </div>
</div>


