<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
    <br />
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>DESCRIPCION</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td><a href="{{ route('categoria.edit', $categoria->id)}}" 
            class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('categoria.destroy', $categoria->id)}}" 
                method="post">
                  <button class="btn btn-danger" type="submit" 
                  onclick="return confirm('Esta seguro de borrar {{$categoria->descripcion}}')" >Del</button>
                </form>
            </td>
        </tr>
    </tbody>
  </table>
<div>


