<?php
$this->form->prepare();
$this->form->setAttribute('action', $this->url('actividad', ['action' => 'resultado']))
        ->setAttribute('method', 'post')
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('role', 'form');
?>

<style>
    .uper{
        margin-top: 40px;
    }
</style>
<div class="card.uper">
	<div class="card-header">
		Agregar Actividad
	</div>
	<div class="card-body">
		<form method="post" action="" enctype="multipart/form-data">


			<div class="form-group">
				<!-- <label for="description">Actividad</label>-->
				<?= $this->form()->formLabel($this->form->get('descripcion'))?>
				<!-- <input type="text" class="form-control" name="descripcion"/> -->
				<?= $this->form()->formInput($this->form->get('descripcion'))?>
				<div style="color: red"><?= $this->formElementErrors($this->form->get('descripcion'))?></div>
			</div>

			<!-- <button type="submit" class="btn btn-primary">Guardar</button> -->
			<?= $this->formSubmit($this->form->get('guardar'))?>
		</form>
	</div><br/>
</div>