<style>
  .uper {
    margin-top: 40px;
  }
</style>

  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>DESCRIPCION</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td></td>
            <td></td>
            <td><a href="" 
            class="btn btn-primary">Edit</a></td>
            <td>
                <form action="" method="post">
                  
                  <button class="btn btn-danger" type="submit" 
                  onclick="" >Del</button>
                </form>
            </td>
        </tr>
        
    </tbody>
  </table>
<div>

