<!--@extends('plantilla')
@section('content')-->
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Agregar ponente
  </div>
  <div class="card-body">
   <!-- @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach-->
        </ul>
      </div><br />
    <!--@endif-->
      <form method="post" action="{{ route('ponente.store') }} " enctype="multipart/form-data">
          <div class="form-group">
              <!--@csrf-->
              <label for="nombrecompleto">Nombre Completo:</label>
              <input type="text" class="form-control" name="nombrecompleto"/>
          </div>
          <div class="form-group">
              <!--@csrf-->
              <label for="sexo">Sexo:</label>
              <input type="text" class="form-control" name="descripcion"/>
          </div>
          <div class="form-group">
              <label for="foto">Foto:</label>
              <input type="file" class="form-control" name="fechainicio"/>
          </div>
          <div class="form-group">
              <label for="cv">Curriculum Vitae:</label>
              <input type="file" class="form-control" name="fechafin"/>
          </div>
          <div class="form-group">
              <label for="nivelacademico">Nivel Academico:</label>
              <input type="text" class="form-control" name="logotipo"/>
          </div>

          <div class="form-group">
              <label for="cuenta">Cuenta:</label>
              <input type="text" class="form-control" name="logotipo"/>
          </div>
          <div class="form-group">
              <label for="password">Password:</label>
              <input type="password" class="form-control" name="password"/>
          </div>
                  
          <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
  </div>
</div>
@endsection