<!--@extends('plantilla')

@section('content')-->
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Editar Categoría
  </div>
  <div class="card-body">
    <!--@if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif-->
      <form method="POST" 
      action="{{ route('ponente.update', $ponente->id) }}" 
      enctype="multipart/form-data">
        <!--{{ csrf_field() }}
        @method('PUT')-->
        <div class="form-group">
              <!--@csrf-->
              <label for="id">Id:</label>
              <input type="text" 
              class="form-control" 
              readonly="true"
               value="{{$ponente->id}}"
              name="id"/>
          </div>

          <div class="form-group">
              <!--@csrf-->
              <label for="nombrecompleto">Nombre Completo:</label>
              <input type="text" 
              value="{{$ponente->nombrecompleto}}"
              class="form-control" 
              name="nombrecompleto"/>
          </div>

          <div class="form-group">
              <!--@csrf-->
              <label for="sexo">Sexo:</label>
              <input type="text" 
              value="{{$ponente->sexo}}"
              class="form-control" 
              name="sexo"/>
          </div>

          <div class="form-group">
             <!-- @csrf-->
              <label for="foto">Foto:</label>
              <input type="file" 
              value="{{$ponente->foto}}"
              class="form-control" 
              name="foto"/>
          </div>
          
         <div class="form-group">
              <!--@csrf-->
              <label for="cv">Curriculum Vitae:</label>
              <input type="file" 
              value="{{$ponente->cv}}"
              class="form-control" 
              name="cv"/>
          </div>

          <div class="form-group">
              <!--@csrf-->
              <label for="nivelacademico">Nivel Academico:</label>
              <input type="file" 
              value="{{$ponente->nivelacademico}}"
              class="form-control" 
              name="nivelacademico"/>
          </div>

          <div class="form-group">
              <!--@csrf-->
              <label for="ccuenta">Cuenta:</label>
              <input type="file" 
              value="{{$ponente->cuenta}}"
              class="form-control" 
              name="cuenta"/>
          </div>

          <div class="form-group">
              <!--@csrf-->
              <label for="password">Password:</label>
              <input type="password" 
              value="{{$ponente->password}}"
              class="form-control" 
              name="password"/>
          </div>
          <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
  </div>
</div>
@endsection

