<?php
$this->form->prepare();
$this->form->setAttribute('action', $this->url('categoria', ['action' => 'registrar']))
        ->setAttribute('method', 'post')
        ->setAttribute('class', 'form-horizontal')
        ->setAttribute('role', 'form');
?>


<style>
    .uper{
        margin-top: 40px;
    }
</style>
<div class="card.uper">
	<div class="card-header">
		Agregar Categoría
	</div>
	<?= $this->titulo ?>
	<div class="card-body">
		<!--<form method="post" action="" enctype="multipart/form-data">-->
		<?= $this->form()->openTag($this->form); ?>

			<div class="form-group">
				<!-- <label for="description">Categoria</label>-->
				<?= $this->formLabel($this->form->get('descripcion')) ?>
				<!-- <input type="text" class="form-control" name="descripcion"/> -->
				<?= $this->formInput($this->form->get('descripcion')) ?>
				<div style="color: red"><?= $this->formElementErrors($this->form->get('descripcion'))?></div>
			</div>

			<!-- <button type="submit" class="btn btn-primary">Guardar</button> -->
			<?= $this->formSubmit($this->form->get('guardar'))?>
			<?= $this->form()->closeTag() ?>
		<!--</form>-->
	</div><br/>
</div>