<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->titulo ?></div>
            <div class="panel-body">

                <table class="table table-striped table-hover" style="width:900px; text-align:left">
                    <tbody>
                        <tr>
                            <td>Descripción:</td>
                            <td><?= $this->actividad->getDescripcion()?></td>
                        </tr>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>