<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Agregar Participante 
  </div>
  <div class="card-body">
      <form method="post" action="" enctype="multipart/form-data">
          <div class="form-group">
              <label for="nombrecompleto">Nombre Completo</label>
              <input type="text" class="form-control" name="nombrecompleto"/>
     
          <label for="CURP">CURP</label>
              <input type="text" class="form-control" name="CURP"/>
          </div>
          <label for="Institucion de Procedencia">Institucion de Procedencia</label>
              <input type="text" class="form-control" name="Institucion de Procedencia"/>
    
          <label for="Cuenta">Cuenta</label>
              <input type="text" class="form-control" name="Cuenta"/>
      
          <label for="Password">Password</label>
              <input type="Password" class="form-control" name="Password"/>
       
              <button type="submit" class="btn btn-primary">Agregar</button>
      </form>
  </div>
  </div>
  
  
  

