<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Editar Participante
  </div>
  <div class="card-body">
      <br />
          <form method="POST" 
      action="{{ route('Participante.update', $Participante->id) }}" 
      enctype="multipart/form-data">

        <div class="form-group">
              <label for="id">Id:</label>
              <input type="text" 
              class="form-control" 
              readonly="true"
              value=""
              name="id"/>
          </div>

          <div class="form-group">
              <label for="nombrecompleto">Nombre Completo:</label>
              <input type="text" 
              value=""
              class="form-control" 
              name="nombrecompleto"/>
          </div>
          <div class="form-group">
              <label for="CURP">CURP:</label>
              <input type="text" 
              value=""
              class="form-control" 
              name="CURP"/>
          </div>
          <div class="form-group">
              <label for="institucionprocedencia">Instutucion de Procedencia:</label>
              <input type="text" 
              value=""
              class="form-control" 
              name="institucionprocedencia"/>
          </div>
          <div class="form-group">
              <label for="Cuenta">Cuenta:</label>
              <input type="text" 
              value=""
              class="form-control" 
              name="Cuenta"/>
          </div>
          <div class="form-group">
              <label for="Password">Password:</label>
              <input type="text" 
              value=""
              class="form-control" 
              name="Password"/>    
          </div>
          </div>
          <button type="submit" class="btn btn-primary">Guardar</button>
      </form>
  </div>
</div>


