<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  
    <div class="alert alert-success">
       
    </div><br />
  
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>NOMBRE COMPLETO</td>
          <td>CURP</td>
          <td>INSTITUCION DE PROCEDENCIA</td>
          <td>CUENTA</td>
          <td>PASSWORD</td>
          <td colspan="8">Action</td>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="{{ route('participante.edit', $participante->id)}}" 
            class="btn btn-primary">Edit</a></td>
            <td>
              <div></div>
                <form action="{{ route('participante-.destroy', $participante->id)}}" 
                method="post">
                  <button class="btn btn-danger" type="submit" 
                  onclick="return confirm('Esta seguro de borrar {{$participante->nombrecompleto}}')" >Del</button>
                </form>
            </td>
        </tr>
    </tbody>
  </table>
<div>
